import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Três sidebars:
 *  - docsSidebar:   conteúdo escrito à mão (guias, arquitetura, motores, CLI…)
 *  - apiSidebar:    referência de API gerada por `npm run gen:docs`
 *  - schemaSidebar: catálogo do schema PostgreSQL gerado por `npm run gen:docs`
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Começando',
      collapsed: false,
      link: {type: 'generated-index', title: 'Começando com o PersonaDB'},
      items: [
        'comecando/instalacao',
        'comecando/primeiro-dataset',
        'comecando/postgresql',
        'comecando/configuracao',
      ],
    },
    {
      type: 'category',
      label: 'Arquitetura',
      link: {type: 'generated-index', title: 'Arquitetura do PersonaDB'},
      items: [
        'arquitetura/visao-geral',
        'arquitetura/determinismo',
        'arquitetura/pipeline',
        'arquitetura/contratos-de-dados',
        'arquitetura/estrutura-de-diretorios',
      ],
    },
    {
      type: 'category',
      label: 'Motores matemáticos',
      link: {type: 'doc', id: 'motores/index'},
      items: [
        'motores/rng',
        'motores/socio',
        'motores/genetics',
        'motores/health',
        'motores/family',
        'motores/geography',
        'motores/criminal',
      ],
    },
    {
      type: 'category',
      label: 'Geradores de domínio',
      link: {type: 'doc', id: 'geradores/index'},
      items: [
        'geradores/contrato',
        'geradores/catalogo',
        'geradores/juncoes-e-metadados',
      ],
    },
    {
      type: 'category',
      label: 'Validadores',
      link: {type: 'doc', id: 'validadores/index'},
      items: ['validadores/relatorio', 'validadores/regras'],
    },
    {
      type: 'category',
      label: 'Dados de referência (seeds)',
      link: {type: 'doc', id: 'seeds/index'},
      items: ['seeds/lookup-data', 'seeds/probability-tables'],
    },
    {
      type: 'category',
      label: 'Linha de comando',
      link: {type: 'generated-index', title: 'Ferramentas de linha de comando'},
      items: [
        'cli/generate',
        'cli/run-validators',
        'cli/export',
        'cli/bulk-insert',
        'cli/benchmark',
        'cli/document-schema',
        'cli/makefile',
      ],
    },
    {
      type: 'category',
      label: 'Guias',
      link: {type: 'generated-index', title: 'Guias práticos'},
      items: [
        'guias/novo-dominio',
        'guias/consultas-sql',
        'guias/testes',
        'guias/desempenho',
        'guias/documentacao',
      ],
    },
    {
      type: 'category',
      label: 'Projeto',
      link: {type: 'generated-index', title: 'Sobre o projeto'},
      items: [
        'projeto/etica-e-limitacoes',
        'projeto/contribuindo',
        'projeto/ci-e-qualidade',
        'projeto/glossario',
      ],
    },
  ],

  apiSidebar: [{type: 'autogenerated', dirName: 'referencia-api'}],

  schemaSidebar: [{type: 'autogenerated', dirName: 'schema'}],
};

export default sidebars;
